### PR TITLE
Allow parallel usage

### LINKED ISSUE #28: Can rcall be used in a parallel setup?
Is there a way that multiple instances of Stata (e.g., using the `parallel` module) can simultaneously call `rcall` without messing each other up? Maybe with the `vanilla` option (and not `debug`)? Are there fixed filenames that are written to (and then which could cause problems)?

### PR DESCRIPTION
**Pull request by bquistorff**
This allows `rcall` to be used simultaneously by different instances of Stata by ensuring that each instance writes to uniquely named files. This is helpful either if one is working on two separate long-running jobs at the same  time or if one parallelizes a task that calls `rcall` (e.g., using the `parallel` module). One has to use the `vanilla` (and not `debug`) option so that files like the history aren't written to. Original filenames are used if someone uses the `debug` option. 

PR note: there's some whitespace changes as I was needing full indentation in order to determine the scope for some of the code blocks. This resolves #28.

### CODE REVIEW

**Comment by haghish** [comment]
I'm a bit in trouble here because I never used the parallel package and I cannot test it. The indention stuff in Stata, __unfortunately__, OS specific (which drives me crazy). The do-file editor is not identical on Mac and Windows and based on your OS you might see the ugly version of the script file. 

Would you like to join the project as a collaborator? You will be able to change the code and add your contributions, I haven't used parallel and won't be able to test your input. But as long as all the torture-tests and example programs run, your addition is most welcomed! Please let me know and I invite you as a collaborator. 

H

**Comment by bquistorff** [comment]
Yes, I'd love to join as a collaborator! I think this is a really nice project and I'm actively using it.

Good point about being able to test the functionality. I'll update this PR to add a test file to `examples`. It's hard to write bullet-proof tests for parallel processing, but probably a good idea to start with at least a minimal one.

**Comment by haghish** [comment]
Ok, please make yourself with `markdoc` package for writing the documentation. I have written a paper about it (if you don't have access, I will email it to you): <https://journals.sagepub.com/doi/abs/10.1177/1536867X20931000>

making sure that `rcall` continues to work is really important, so it might be a good idea to create another branch in the project and implement all of your code and documentation in it and once it becomes bulletproof, we merge it. 

And most importantly, welcome to `rcall`, so glad that the project has caught another programmers attention.

**Comment by haghish** [comment]
I sent you an invitation.

**Pull request closed without merging**
